#ifndef IMPORTER_PREREQUISITES_H
#define IMPORTER_PREREQUISITES_H

#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../ThirdParty/tiny_gltf.h"

#endif
